version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/backend' # Location of package manifests
    schedule:
      interval: 'weekly'
    assignees:
      - 'kajyr'
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/frontend' # Location of package manifests
    schedule:
      interval: 'weekly'
    assignees:
      - 'kajyr'
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/common' # Location of package manifests
    schedule:
      interval: 'weekly'
    assignees:
      - 'kajyr'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'dependencies'
    assignees:
      - 'kajyr'
