name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo "nvmrc=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.nvmrc }}'
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ steps.nvm.outputs.nvmrc }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run build
      - run: npm test
